var mentor1 = "Daniel";
var mentor2 = "Irina";
var mentor3 = "Mimi";
var mentor4 = "Rob";
var mentor5 = "Yohannes";
console.log(mentor1,mentor2,mentor3,mentor4,mentor5);
console.log("Hello",mentor1);
console.log("Hello",mentor2);
console.log("Hello",mentor3);
console.log("Hello",mentor4);
console.log("Hello",mentor5);